### ISSUE TITLE
Create an Empty Events page and setup routes/navbar

### ISSUE THREAD

**Issue by supesh-sinha** [supesh-sinha/Fintech-Website#2]
Create an Empty Events page. Setup its routes and add the navbar and footer. The page should just contain events written on it.

**Comment by 0xlarmideh** [comment]
@supesh-sinha Can I work on this

**Comment by supeshsinha** [comment]
I will take it up

**Comment by supesh-sinha** [comment]
> @supesh-sinha Can I work on this

Sorry but this repo is open only for students of IIT (ISM) Dhanbad. 
Best Wishes for you open source journey

**Comment by supesh-sinha** [comment]
Well it was not the homepage, but anyways the issue is solved
